# Generated by Django 4.0.6 on 2024-05-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0004_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='nomre',
        ),
        migrations.AddField(
            model_name='pais',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pais',
            name='capital',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pais',
            name='continente',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pais',
            name='id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
