# Generated by Django 4.0.6 on 2024-05-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0005_remove_pais_nomre_pais_nombre_alter_pais_capital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='capital',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pais',
            name='continente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pais',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
