# Generated by Django 4.0.6 on 2024-06-05 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0008_alter_pelicula_duracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='pasi',
            new_name='pais',
        ),
    ]
